version: "3"

networks:
    application:
        driver: bridge
volumes:           
    storage-kafka:

        name: storage-kafka

        driver: local

    storage-zookeeper:

        name: storage-zookeeper

        driver: local

    storage-zookeeper-log:

        name: storage-zookeeper-log

        driver: local
services:    
    redis:
        image: redis
        container_name: redis
        command: redis-server --requirepass redis123!
        ports: 
            - "6379:6379"
    mssql-tiny:
        image: justin2004/mssql_server_tiny
        container_name: sql-server-tiny
        ports:
            - '1433:1433'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Secret1234
        depends_on:
            - redis
        volumes:
            - './drive/data:/var/opt/mssql/data'
        networks:
            - application 
    zookeeper:
        image: confluentinc/cp-zookeeper:6.0.0
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        volumes:

            - storage-zookeeper:/var/lib/zookeeper/data

            - storage-zookeeper-log:/var/lib/zookeeper/log
    kafka:
        image: confluentinc/cp-kafka:6.0.0
        hostname: kafka
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "29092:29092"
            - "9092:9092"
            - "9101:9101"
        volumes:
            - storage-kafka:/var/lib/kafka/data
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_JMX_PORT: 9101
            KAFKA_JMX_HOSTNAME: localhost
            KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
            CONFLUENT_METRICS_ENABLE: 'true'
    schema-registry:
        image: confluentinc/cp-schema-registry:6.0.0
        hostname: schema-registry
        container_name: schema-registry
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8081 || exit 1"]
            interval: 1s
            timeout: 10s
            retries: 3
            start_period: 40s
        depends_on:
            - kafka
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
            SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081                        